// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: internal/contracts/grpc/quant/v1/quant_engine.proto

package quantv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QuantEngineService_EvaluateSignal_FullMethodName          = "/quant.v1.QuantEngineService/EvaluateSignal"
	QuantEngineService_CalculateFeatures_FullMethodName       = "/quant.v1.QuantEngineService/CalculateFeatures"
	QuantEngineService_AnalyzeMarketRegime_FullMethodName     = "/quant.v1.QuantEngineService/AnalyzeMarketRegime"
	QuantEngineService_EvaluateModel_FullMethodName           = "/quant.v1.QuantEngineService/EvaluateModel"
	QuantEngineService_RegisterDecisionOutcome_FullMethodName = "/quant.v1.QuantEngineService/RegisterDecisionOutcome"
	QuantEngineService_ValidateStrategy_FullMethodName        = "/quant.v1.QuantEngineService/ValidateStrategy"
	QuantEngineService_RunBacktest_FullMethodName             = "/quant.v1.QuantEngineService/RunBacktest"
	QuantEngineService_GetBacktestResult_FullMethodName       = "/quant.v1.QuantEngineService/GetBacktestResult"
	QuantEngineService_StreamBacktestProgress_FullMethodName  = "/quant.v1.QuantEngineService/StreamBacktestProgress"
	QuantEngineService_RunOptimization_FullMethodName         = "/quant.v1.QuantEngineService/RunOptimization"
	QuantEngineService_GetOptimizationResult_FullMethodName   = "/quant.v1.QuantEngineService/GetOptimizationResult"
	QuantEngineService_ExportDataset_FullMethodName           = "/quant.v1.QuantEngineService/ExportDataset"
	QuantEngineService_GetFeatureSchema_FullMethodName        = "/quant.v1.QuantEngineService/GetFeatureSchema"
	QuantEngineService_GetModelMetadata_FullMethodName        = "/quant.v1.QuantEngineService/GetModelMetadata"
	QuantEngineService_ReloadApprovedModel_FullMethodName     = "/quant.v1.QuantEngineService/ReloadApprovedModel"
)

// QuantEngineServiceClient is the client API for QuantEngineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuantEngineServiceClient interface {
	EvaluateSignal(ctx context.Context, in *EvaluateSignalRequest, opts ...grpc.CallOption) (*EvaluateSignalResponse, error)
	CalculateFeatures(ctx context.Context, in *CalculateFeaturesRequest, opts ...grpc.CallOption) (*CalculateFeaturesResponse, error)
	AnalyzeMarketRegime(ctx context.Context, in *AnalyzeMarketRegimeRequest, opts ...grpc.CallOption) (*AnalyzeMarketRegimeResponse, error)
	EvaluateModel(ctx context.Context, in *EvaluateModelRequest, opts ...grpc.CallOption) (*EvaluateModelResponse, error)
	RegisterDecisionOutcome(ctx context.Context, in *RegisterDecisionOutcomeRequest, opts ...grpc.CallOption) (*RegisterDecisionOutcomeResponse, error)
	ValidateStrategy(ctx context.Context, in *ValidateStrategyRequest, opts ...grpc.CallOption) (*ValidateStrategyResponse, error)
	RunBacktest(ctx context.Context, in *RunBacktestRequest, opts ...grpc.CallOption) (*RunBacktestResponse, error)
	GetBacktestResult(ctx context.Context, in *GetBacktestResultRequest, opts ...grpc.CallOption) (*GetBacktestResultResponse, error)
	StreamBacktestProgress(ctx context.Context, in *StreamBacktestProgressRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BacktestProgressResponse], error)
	RunOptimization(ctx context.Context, in *RunOptimizationRequest, opts ...grpc.CallOption) (*RunOptimizationResponse, error)
	GetOptimizationResult(ctx context.Context, in *GetOptimizationResultRequest, opts ...grpc.CallOption) (*GetOptimizationResultResponse, error)
	ExportDataset(ctx context.Context, in *ExportDatasetRequest, opts ...grpc.CallOption) (*ExportDatasetResponse, error)
	GetFeatureSchema(ctx context.Context, in *GetFeatureSchemaRequest, opts ...grpc.CallOption) (*GetFeatureSchemaResponse, error)
	GetModelMetadata(ctx context.Context, in *GetModelMetadataRequest, opts ...grpc.CallOption) (*GetModelMetadataResponse, error)
	ReloadApprovedModel(ctx context.Context, in *ReloadApprovedModelRequest, opts ...grpc.CallOption) (*ReloadApprovedModelResponse, error)
}

type quantEngineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQuantEngineServiceClient(cc grpc.ClientConnInterface) QuantEngineServiceClient {
	return &quantEngineServiceClient{cc}
}

func (c *quantEngineServiceClient) EvaluateSignal(ctx context.Context, in *EvaluateSignalRequest, opts ...grpc.CallOption) (*EvaluateSignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluateSignalResponse)
	err := c.cc.Invoke(ctx, QuantEngineService_EvaluateSignal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quantEngineServiceClient) CalculateFeatures(ctx context.Context, in *CalculateFeaturesRequest, opts ...grpc.CallOption) (*CalculateFeaturesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateFeaturesResponse)
	err := c.cc.Invoke(ctx, QuantEngineService_CalculateFeatures_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quantEngineServiceClient) AnalyzeMarketRegime(ctx context.Context, in *AnalyzeMarketRegimeRequest, opts ...grpc.CallOption) (*AnalyzeMarketRegimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeMarketRegimeResponse)
	err := c.cc.Invoke(ctx, QuantEngineService_AnalyzeMarketRegime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quantEngineServiceClient) EvaluateModel(ctx context.Context, in *EvaluateModelRequest, opts ...grpc.CallOption) (*EvaluateModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluateModelResponse)
	err := c.cc.Invoke(ctx, QuantEngineService_EvaluateModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quantEngineServiceClient) RegisterDecisionOutcome(ctx context.Context, in *RegisterDecisionOutcomeRequest, opts ...grpc.CallOption) (*RegisterDecisionOutcomeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterDecisionOutcomeResponse)
	err := c.cc.Invoke(ctx, QuantEngineService_RegisterDecisionOutcome_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quantEngineServiceClient) ValidateStrategy(ctx context.Context, in *ValidateStrategyRequest, opts ...grpc.CallOption) (*ValidateStrategyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateStrategyResponse)
	err := c.cc.Invoke(ctx, QuantEngineService_ValidateStrategy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quantEngineServiceClient) RunBacktest(ctx context.Context, in *RunBacktestRequest, opts ...grpc.CallOption) (*RunBacktestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunBacktestResponse)
	err := c.cc.Invoke(ctx, QuantEngineService_RunBacktest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quantEngineServiceClient) GetBacktestResult(ctx context.Context, in *GetBacktestResultRequest, opts ...grpc.CallOption) (*GetBacktestResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBacktestResultResponse)
	err := c.cc.Invoke(ctx, QuantEngineService_GetBacktestResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quantEngineServiceClient) StreamBacktestProgress(ctx context.Context, in *StreamBacktestProgressRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BacktestProgressResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &QuantEngineService_ServiceDesc.Streams[0], QuantEngineService_StreamBacktestProgress_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamBacktestProgressRequest, BacktestProgressResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QuantEngineService_StreamBacktestProgressClient = grpc.ServerStreamingClient[BacktestProgressResponse]

func (c *quantEngineServiceClient) RunOptimization(ctx context.Context, in *RunOptimizationRequest, opts ...grpc.CallOption) (*RunOptimizationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunOptimizationResponse)
	err := c.cc.Invoke(ctx, QuantEngineService_RunOptimization_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quantEngineServiceClient) GetOptimizationResult(ctx context.Context, in *GetOptimizationResultRequest, opts ...grpc.CallOption) (*GetOptimizationResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOptimizationResultResponse)
	err := c.cc.Invoke(ctx, QuantEngineService_GetOptimizationResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quantEngineServiceClient) ExportDataset(ctx context.Context, in *ExportDatasetRequest, opts ...grpc.CallOption) (*ExportDatasetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportDatasetResponse)
	err := c.cc.Invoke(ctx, QuantEngineService_ExportDataset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quantEngineServiceClient) GetFeatureSchema(ctx context.Context, in *GetFeatureSchemaRequest, opts ...grpc.CallOption) (*GetFeatureSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFeatureSchemaResponse)
	err := c.cc.Invoke(ctx, QuantEngineService_GetFeatureSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quantEngineServiceClient) GetModelMetadata(ctx context.Context, in *GetModelMetadataRequest, opts ...grpc.CallOption) (*GetModelMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetModelMetadataResponse)
	err := c.cc.Invoke(ctx, QuantEngineService_GetModelMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quantEngineServiceClient) ReloadApprovedModel(ctx context.Context, in *ReloadApprovedModelRequest, opts ...grpc.CallOption) (*ReloadApprovedModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReloadApprovedModelResponse)
	err := c.cc.Invoke(ctx, QuantEngineService_ReloadApprovedModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuantEngineServiceServer is the server API for QuantEngineService service.
// All implementations must embed UnimplementedQuantEngineServiceServer
// for forward compatibility.
type QuantEngineServiceServer interface {
	EvaluateSignal(context.Context, *EvaluateSignalRequest) (*EvaluateSignalResponse, error)
	CalculateFeatures(context.Context, *CalculateFeaturesRequest) (*CalculateFeaturesResponse, error)
	AnalyzeMarketRegime(context.Context, *AnalyzeMarketRegimeRequest) (*AnalyzeMarketRegimeResponse, error)
	EvaluateModel(context.Context, *EvaluateModelRequest) (*EvaluateModelResponse, error)
	RegisterDecisionOutcome(context.Context, *RegisterDecisionOutcomeRequest) (*RegisterDecisionOutcomeResponse, error)
	ValidateStrategy(context.Context, *ValidateStrategyRequest) (*ValidateStrategyResponse, error)
	RunBacktest(context.Context, *RunBacktestRequest) (*RunBacktestResponse, error)
	GetBacktestResult(context.Context, *GetBacktestResultRequest) (*GetBacktestResultResponse, error)
	StreamBacktestProgress(*StreamBacktestProgressRequest, grpc.ServerStreamingServer[BacktestProgressResponse]) error
	RunOptimization(context.Context, *RunOptimizationRequest) (*RunOptimizationResponse, error)
	GetOptimizationResult(context.Context, *GetOptimizationResultRequest) (*GetOptimizationResultResponse, error)
	ExportDataset(context.Context, *ExportDatasetRequest) (*ExportDatasetResponse, error)
	GetFeatureSchema(context.Context, *GetFeatureSchemaRequest) (*GetFeatureSchemaResponse, error)
	GetModelMetadata(context.Context, *GetModelMetadataRequest) (*GetModelMetadataResponse, error)
	ReloadApprovedModel(context.Context, *ReloadApprovedModelRequest) (*ReloadApprovedModelResponse, error)
	mustEmbedUnimplementedQuantEngineServiceServer()
}

// UnimplementedQuantEngineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQuantEngineServiceServer struct{}

func (UnimplementedQuantEngineServiceServer) EvaluateSignal(context.Context, *EvaluateSignalRequest) (*EvaluateSignalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EvaluateSignal not implemented")
}
func (UnimplementedQuantEngineServiceServer) CalculateFeatures(context.Context, *CalculateFeaturesRequest) (*CalculateFeaturesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateFeatures not implemented")
}
func (UnimplementedQuantEngineServiceServer) AnalyzeMarketRegime(context.Context, *AnalyzeMarketRegimeRequest) (*AnalyzeMarketRegimeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeMarketRegime not implemented")
}
func (UnimplementedQuantEngineServiceServer) EvaluateModel(context.Context, *EvaluateModelRequest) (*EvaluateModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EvaluateModel not implemented")
}
func (UnimplementedQuantEngineServiceServer) RegisterDecisionOutcome(context.Context, *RegisterDecisionOutcomeRequest) (*RegisterDecisionOutcomeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterDecisionOutcome not implemented")
}
func (UnimplementedQuantEngineServiceServer) ValidateStrategy(context.Context, *ValidateStrategyRequest) (*ValidateStrategyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateStrategy not implemented")
}
func (UnimplementedQuantEngineServiceServer) RunBacktest(context.Context, *RunBacktestRequest) (*RunBacktestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunBacktest not implemented")
}
func (UnimplementedQuantEngineServiceServer) GetBacktestResult(context.Context, *GetBacktestResultRequest) (*GetBacktestResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBacktestResult not implemented")
}
func (UnimplementedQuantEngineServiceServer) StreamBacktestProgress(*StreamBacktestProgressRequest, grpc.ServerStreamingServer[BacktestProgressResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamBacktestProgress not implemented")
}
func (UnimplementedQuantEngineServiceServer) RunOptimization(context.Context, *RunOptimizationRequest) (*RunOptimizationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunOptimization not implemented")
}
func (UnimplementedQuantEngineServiceServer) GetOptimizationResult(context.Context, *GetOptimizationResultRequest) (*GetOptimizationResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOptimizationResult not implemented")
}
func (UnimplementedQuantEngineServiceServer) ExportDataset(context.Context, *ExportDatasetRequest) (*ExportDatasetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportDataset not implemented")
}
func (UnimplementedQuantEngineServiceServer) GetFeatureSchema(context.Context, *GetFeatureSchemaRequest) (*GetFeatureSchemaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFeatureSchema not implemented")
}
func (UnimplementedQuantEngineServiceServer) GetModelMetadata(context.Context, *GetModelMetadataRequest) (*GetModelMetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModelMetadata not implemented")
}
func (UnimplementedQuantEngineServiceServer) ReloadApprovedModel(context.Context, *ReloadApprovedModelRequest) (*ReloadApprovedModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReloadApprovedModel not implemented")
}
func (UnimplementedQuantEngineServiceServer) mustEmbedUnimplementedQuantEngineServiceServer() {}
func (UnimplementedQuantEngineServiceServer) testEmbeddedByValue()                            {}

// UnsafeQuantEngineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuantEngineServiceServer will
// result in compilation errors.
type UnsafeQuantEngineServiceServer interface {
	mustEmbedUnimplementedQuantEngineServiceServer()
}

func RegisterQuantEngineServiceServer(s grpc.ServiceRegistrar, srv QuantEngineServiceServer) {
	// If the following call panics, it indicates UnimplementedQuantEngineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QuantEngineService_ServiceDesc, srv)
}

func _QuantEngineService_EvaluateSignal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateSignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuantEngineServiceServer).EvaluateSignal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuantEngineService_EvaluateSignal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuantEngineServiceServer).EvaluateSignal(ctx, req.(*EvaluateSignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuantEngineService_CalculateFeatures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateFeaturesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuantEngineServiceServer).CalculateFeatures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuantEngineService_CalculateFeatures_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuantEngineServiceServer).CalculateFeatures(ctx, req.(*CalculateFeaturesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuantEngineService_AnalyzeMarketRegime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeMarketRegimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuantEngineServiceServer).AnalyzeMarketRegime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuantEngineService_AnalyzeMarketRegime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuantEngineServiceServer).AnalyzeMarketRegime(ctx, req.(*AnalyzeMarketRegimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuantEngineService_EvaluateModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuantEngineServiceServer).EvaluateModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuantEngineService_EvaluateModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuantEngineServiceServer).EvaluateModel(ctx, req.(*EvaluateModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuantEngineService_RegisterDecisionOutcome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDecisionOutcomeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuantEngineServiceServer).RegisterDecisionOutcome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuantEngineService_RegisterDecisionOutcome_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuantEngineServiceServer).RegisterDecisionOutcome(ctx, req.(*RegisterDecisionOutcomeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuantEngineService_ValidateStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateStrategyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuantEngineServiceServer).ValidateStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuantEngineService_ValidateStrategy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuantEngineServiceServer).ValidateStrategy(ctx, req.(*ValidateStrategyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuantEngineService_RunBacktest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunBacktestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuantEngineServiceServer).RunBacktest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuantEngineService_RunBacktest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuantEngineServiceServer).RunBacktest(ctx, req.(*RunBacktestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuantEngineService_GetBacktestResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBacktestResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuantEngineServiceServer).GetBacktestResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuantEngineService_GetBacktestResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuantEngineServiceServer).GetBacktestResult(ctx, req.(*GetBacktestResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuantEngineService_StreamBacktestProgress_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamBacktestProgressRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QuantEngineServiceServer).StreamBacktestProgress(m, &grpc.GenericServerStream[StreamBacktestProgressRequest, BacktestProgressResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QuantEngineService_StreamBacktestProgressServer = grpc.ServerStreamingServer[BacktestProgressResponse]

func _QuantEngineService_RunOptimization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunOptimizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuantEngineServiceServer).RunOptimization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuantEngineService_RunOptimization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuantEngineServiceServer).RunOptimization(ctx, req.(*RunOptimizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuantEngineService_GetOptimizationResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOptimizationResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuantEngineServiceServer).GetOptimizationResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuantEngineService_GetOptimizationResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuantEngineServiceServer).GetOptimizationResult(ctx, req.(*GetOptimizationResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuantEngineService_ExportDataset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportDatasetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuantEngineServiceServer).ExportDataset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuantEngineService_ExportDataset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuantEngineServiceServer).ExportDataset(ctx, req.(*ExportDatasetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuantEngineService_GetFeatureSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeatureSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuantEngineServiceServer).GetFeatureSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuantEngineService_GetFeatureSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuantEngineServiceServer).GetFeatureSchema(ctx, req.(*GetFeatureSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuantEngineService_GetModelMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuantEngineServiceServer).GetModelMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuantEngineService_GetModelMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuantEngineServiceServer).GetModelMetadata(ctx, req.(*GetModelMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuantEngineService_ReloadApprovedModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadApprovedModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuantEngineServiceServer).ReloadApprovedModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuantEngineService_ReloadApprovedModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuantEngineServiceServer).ReloadApprovedModel(ctx, req.(*ReloadApprovedModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QuantEngineService_ServiceDesc is the grpc.ServiceDesc for QuantEngineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuantEngineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quant.v1.QuantEngineService",
	HandlerType: (*QuantEngineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EvaluateSignal",
			Handler:    _QuantEngineService_EvaluateSignal_Handler,
		},
		{
			MethodName: "CalculateFeatures",
			Handler:    _QuantEngineService_CalculateFeatures_Handler,
		},
		{
			MethodName: "AnalyzeMarketRegime",
			Handler:    _QuantEngineService_AnalyzeMarketRegime_Handler,
		},
		{
			MethodName: "EvaluateModel",
			Handler:    _QuantEngineService_EvaluateModel_Handler,
		},
		{
			MethodName: "RegisterDecisionOutcome",
			Handler:    _QuantEngineService_RegisterDecisionOutcome_Handler,
		},
		{
			MethodName: "ValidateStrategy",
			Handler:    _QuantEngineService_ValidateStrategy_Handler,
		},
		{
			MethodName: "RunBacktest",
			Handler:    _QuantEngineService_RunBacktest_Handler,
		},
		{
			MethodName: "GetBacktestResult",
			Handler:    _QuantEngineService_GetBacktestResult_Handler,
		},
		{
			MethodName: "RunOptimization",
			Handler:    _QuantEngineService_RunOptimization_Handler,
		},
		{
			MethodName: "GetOptimizationResult",
			Handler:    _QuantEngineService_GetOptimizationResult_Handler,
		},
		{
			MethodName: "ExportDataset",
			Handler:    _QuantEngineService_ExportDataset_Handler,
		},
		{
			MethodName: "GetFeatureSchema",
			Handler:    _QuantEngineService_GetFeatureSchema_Handler,
		},
		{
			MethodName: "GetModelMetadata",
			Handler:    _QuantEngineService_GetModelMetadata_Handler,
		},
		{
			MethodName: "ReloadApprovedModel",
			Handler:    _QuantEngineService_ReloadApprovedModel_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamBacktestProgress",
			Handler:       _QuantEngineService_StreamBacktestProgress_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/contracts/grpc/quant/v1/quant_engine.proto",
}
